;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	corfu-previous
	end-of-visual-line
	forward-sexp
	org-return-and-maybe-indent
	vundo
	))

(setq mc/cmds-to-run-once
      '(
	my/backward-kill-spaces-or-char-or-word
	org-self-insert-command
	save-buffers-kill-terminal
	))
