;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        completion-preview-insert
        consult-yank-pop
        end-of-visual-line
        handle-switch-frame
        indent-for-tab-command
        lsp-ui-doc--handle-mouse-movement
        mark-sexp
        multiple-cursors-mode
        my/backward-kill-spaces-or-char-or-word
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-yank
        pixel-scroll-precision
        read-only-mode
        surround-insert
        suspend-frame
        text-scale-adjust
        text-scale-decrease
        ))

(setq mc/cmds-to-run-once
      '(
        kill-region
        undefined
        xref-find-definitions
        ))
